# https://docs.github.com/en/code-security/supply-chain-security/keeping-your-dependencies-updated-automatically/configuration-options-for-dependency-updates#package-ecosystem
version: 2
updates:
  # Enable version updates for Python
  - package-ecosystem: "uv"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "weekly"
    labels:
      - "dependencies"
  # Enable updates for Github Actions
  - package-ecosystem: "github-actions"
    target-branch: "develop"
    directory: "/"
    schedule:
      interval: "monthly"
    labels:
      - "dependencies"
