# https://beta.ruff.rs/docs/settings/
# https://beta.ruff.rs/docs/rules/
extend-select = ["I", "W", "UP", "COM", "EXE", "ISC", "ICN", "G201", "INP", "PIE", "RSE", "SIM", "TID", "PLC", "PLE", "RUF", "PTH"]
fix = true
line-length = 110
respect-gitignore = true
target-version = "py310"
output-format = "grouped"
show-fixes = true

[isort]
force-single-line = true
