# https://beta.ruff.rs/docs/settings/
fix = true
line-length = 110
respect-gitignore = true
target-version = "py310"
output-format = "grouped"
show-fixes = true

[lint]
# https://docs.astral.sh/ruff/rules/
extend-select = ["F", "E", "W", "I", "UP", "COM", "EXE", "ISC", "ICN", "G201", "INP", "PIE", "RSE", "SIM", "TID", "PLC", "PLE", "RUF", "PTH"]

[lint.isort]
force-single-line = true
