[project]
name = "image-cleaner-action"
version = "0.12.0"
description = "Tools to cleanup old ghcr.io images when the source is removed"
readme = "README.md"
requires-python = ">=3.13"
classifiers = [
  "Programming Language :: Python :: 3 :: Only",
  "Programming Language :: Python :: 3.13",
  "Programming Language :: Python :: 3.14",
  "Programming Language :: Python :: 3.15",
]
dependencies = [
  "github-action-utils>=1.1",
  "httpx[brotli,http2]>=0.28",
  "httpx-retries",
]

[dependency-groups]
dev = [
  "coverage[toml]~=7.8",
  "mypy",
  "pre-commit",
  "pre-commit-uv",
  "pytest",
  "pytest-asyncio",
  "pytest-cov",
  "pytest-httpx",
  "pytest-mock",
  "pytest-randomly",
  "pytest-sugar",
  "ruff",
]

[tool.uv]
required-version = ">=0.9.0"
package = false

[tool.ruff]
target-version = "py313"
line-length = 110
respect-gitignore = true
# https://docs.astral.sh/ruff/settings/
fix = true
show-fixes = true
output-format = "grouped"
# https://docs.astral.sh/ruff/rules/
lint.extend-select = [
  "ASYNC",
  "COM",
  "E",
  "EXE",
  "F",
  "G201",
  "I",
  "ICN",
  "INP",
  "ISC",
  "PIE",
  "PLC",
  "PLE",
  "PTH",
  "RSE",
  "RUF",
  "SIM",
  "TID",
  "UP",
  "W",
]
lint.per-file-ignores."github/models/**" = [ "E501" ]
# https://docs.astral.sh/ruff/settings/#lintisort
lint.isort.force-single-line = true

[tool.mypy]
python_version = "3.13"

[tool.pytest]
addopts = [ "--import-mode=importlib", "--cov" ]
minversion = "9.0"
pythonpath = [ "." ]
testpaths = [ "tests" ]

[tool.coverage]
run.source_pkgs = [ "github", "regtools", "tests", "utils" ]
run.omit = [
  "src/version/__init__.py",
  "tests/conftest.py",
  "tests/utils.py",
]
run.branch = true
run.parallel = true
paths.actions = [ "github", "regtools", "utils" ]
paths.tests = [ "tests" ]
report.exclude_lines = [
  "if __name__ == '__main__':",
  "if SAVE_OUTPUTS:",
  "if TYPE_CHECKING:",
  "no cov",
]
