name: 'Ephemeral Image Cleaner'
description: 'A GitHub Action that cleans up the ghcr.io registry of old images, once the image source is gone'
inputs:
  scheme:
    description: 'Choose the image naming scheme either "branch" or "pull_request"'
    required: true
    default: "branch"
  package_name:
    description: 'The name of the container package to clean'
    required: true
  is_org:
    description: 'True if the package owner is an organization, False otherwise'
    required: true
    default: "false"
  tag_match_regex:
    description: 'The regular expression to use for matching your temporary image tagging scheme'
    required: true
  do_delete:
    description: 'If true, actually delete packages'
    required: true
  log_level:
    description: 'Control the log level'
    default: "info"
runs:
  using: 'composite'
  steps:
    -
      name: Install Python
      uses: actions/setup-python@v4
      id: setup-python
      with:
        python-version: '3.10'
        cache: "pipenv"
        cache-dependency-path: 'Pipfile.lock'
    -
      name: Install pipenv
      shell: bash
      run: |
        pip install --user pipenv==2023.3.20
    -
      name: Install dependencies
      shell: bash
      run: |
        pipenv --python ${{ steps.setup-python.outputs.python-version }} sync
    -
      name: List installed dependencies
      shell: bash
      run: |
        pipenv --python ${{ steps.setup-python.outputs.python-version }} run pip list
    -
      name: Fetch the number's square
      shell: bash
      id: get-square
      run: |
        pipenv --python ${{ steps.setup-python.outputs.python-version }} run \
          main.py \
            --scheme ${{ inputs.scheme }} \
            --loglevel ${{ inputs.log_level }} \
            --regex-str ${{ inputs.tag_match_regex }} \
            --name ${{ inputs.package_name }} \
            --is-org ${{ inputs.is_org }}
