name: 'Untagged Image Cleaner'
description: 'A GitHub Action that cleans up the ghcr.io registry of untagged images'
inputs:
  token:
    description: 'The Personal Access Token for deleting packages'
    required: true
  owner:
    description: 'The owner of the package'
    required: true
  is_org:
    description: 'True if the package owner is an organization, False otherwise'
    required: true
    default: "false"
  package_name:
    description: 'The name of the container package to clean'
    required: true
  do_delete:
    description: 'If true, actually delete packages'
    required: true
    default: "false"
  log_level:
    description: 'Control the log level'
    default: "info"
runs:
  using: 'composite'
  steps:
    -
      name: Install Python
      uses: actions/setup-python@v5
      id: setup-python
      with:
        python-version: '3.12'
    -
      name: Install uv
      uses: astral-sh/setup-uv@v6.8.0
      with:
        version: "0.8.x"
        python-version: ${{ steps.setup-python.outputs.python-version }}
    -
      name: Clean the images
      shell: bash
      id: untagged-image-clean
      run: |
        cd  ${{ github.action_path }}/..
        uv run \
          --frozen \
          --quiet \
          --no-python-downloads \
          --no-dev \
          --python ${{ steps.setup-python.outputs.python-version }} \
          ${{ github.action_path }}/../main_untagged.py \
          --token "${{ inputs.token }}" \
          --owner "${{ inputs.owner }}" \
          --is-org "${{ inputs.is_org }}" \
          --name "${{ inputs.package_name }}" \
          --delete "${{ inputs.do_delete }}" \
          --loglevel "${{ inputs.log_level }}"
