# generated by datamodel-codegen:
#   filename:  input.json
#   timestamp: 2025-10-03T16:26:40+00:00

from __future__ import annotations

from typing import Literal
from typing import NotRequired
from typing import TypedDict


class Container(TypedDict):
    tags: list[str]


class Docker(TypedDict):
    tag: NotRequired[list[str]]


class Metadata(TypedDict):
    package_type: Literal["npm", "maven", "rubygems", "docker", "nuget", "container"]
    container: NotRequired[Container]
    docker: NotRequired[Docker]


class Package(TypedDict):
    """
    A version of a software package
    """

    id: int
    """
    Unique identifier of the package version.
    """
    name: str
    """
    The name of the package version.
    """
    url: str
    package_html_url: str
    html_url: NotRequired[str]
    license: NotRequired[str]
    description: NotRequired[str]
    created_at: str
    updated_at: str
    deleted_at: NotRequired[str]
    metadata: NotRequired[Metadata]
