# generated by datamodel-codegen:
#   filename:  input.json
#   timestamp: 2025-10-02T16:58:31+00:00

from __future__ import annotations

from typing import NotRequired
from typing import TypedDict


class Core(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class Graphql(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class Search(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class CodeSearch(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class SourceImport(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class IntegrationManifest(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class CodeScanningUpload(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class ActionsRunnerRegistration(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class Scim(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class DependencySnapshots(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class DependencySbom(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class CodeScanningAutofix(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class Resources(TypedDict):
    core: Core
    graphql: NotRequired[Graphql]
    search: Search
    code_search: NotRequired[CodeSearch]
    source_import: NotRequired[SourceImport]
    integration_manifest: NotRequired[IntegrationManifest]
    code_scanning_upload: NotRequired[CodeScanningUpload]
    actions_runner_registration: NotRequired[ActionsRunnerRegistration]
    scim: NotRequired[Scim]
    dependency_snapshots: NotRequired[DependencySnapshots]
    dependency_sbom: NotRequired[DependencySbom]
    code_scanning_autofix: NotRequired[CodeScanningAutofix]


class Rate(TypedDict):
    limit: int
    remaining: int
    reset: int
    used: int


class RateLimitOverview(TypedDict):
    """
    Rate Limit Overview
    """

    resources: Resources
    rate: Rate
