name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Check files
        uses: pre-commit/action@v3.0.1
  tests:
    name: tests
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Install Python
        uses: actions/setup-python@v5
        id: setup-python
        with:
          python-version: '3.12'
      -
        name: Install uv
        uses: astral-sh/setup-uv@v6.1.0
        with:
          version: "0.7.x"
          python-version: ${{ steps.setup-python.outputs.python-version }}
      -
        name: Run tests
        run: |
          uv sync --dev
          uv run pytest
  create-release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - lint
      - tests
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: ${{ github.ref_name }}
      -
        name: Display release info
        run: |
          echo "Version: ${{ steps.query-release-info.outputs.version }}"
          echo "Date: ${{ steps.query-release-info.outputs.release-date }}"
          echo "${{ steps.query-release-info.outputs.release-notes }}"
      -
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
