name: CI

on:
  push:
  pull_request:

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v4
      -
        name: Check files
        uses: pre-commit/action@v3.0.0
  create-release:
    name: Release
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs:
      - lint
    steps:
      -
        uses: actions/checkout@v4
      -
        name: Get latest release info
        id: query-release-info
        uses: release-flow/keep-a-changelog-action@v3
        with:
          command: query
          version: ${{ github.ref_name }}
      -
        name: Display release info
        run: |
          echo "Version: ${{ steps.query-release-info.outputs.version }}"
          echo "Date: ${{ steps.query-release-info.outputs.release-date }}"
          echo "${{ steps.query-release-info.outputs.release-notes }}"
      -
        uses: ncipollo/release-action@v1
        with:
          body: ${{ steps.query-release-info.outputs.release-notes }}
