name: lint

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  pre-commit:
    name: Linting Checks
    runs-on: ubuntu-22.04
    steps:
      -
        name: Checkout repository
        uses: actions/checkout@v3
      -
        name: Install python
        uses: actions/setup-python@v4
        with:
          python-version: "3.10"
      -
        name: Check files
        uses: pre-commit/action@v3.0.0
